---
title: "Japan Map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(rvest)
library(DT)
```

## Volcano
======================================================

Column 
-----------------------------------------------------------------------

### Volcanos in Japan

```{r}

dat<-read.csv("volcano_list.csv", fileEncoding = "UTF-8")


dat %>% 
  filter(NAME != "") %>% 
  separate(lat, into=c("lat_d", "lat_m", "lat_s"), sep="([°′″])") %>% 
  mutate(lat=as.numeric(lat_d) + as.numeric(lat_m)/60 + as.numeric(lat_s)/3600) %>% 
  separate(lng, into=c("lng_d", "lng_m", "lng_s"), sep="([°′″])") %>% 
  mutate(lng=as.numeric(lng_d) + as.numeric(lng_m)/60 + as.numeric(lng_s)/3600) %>% 
  leaflet() %>% 
  addTiles(
    urlTemplate = 'http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'
  ) %>% 
  addCircleMarkers(lat=~lat, lng=~lng, radius = ~elev/300, label = ~NAME, color="red") 


```

## Japan 100 famous mountain(2021)
===============================================

Column {data-width=60%}
--------------------------------------

### Map

```{r 100moutain}

x <- read.csv("http://www.dinov.tokyo/Data/JP_Pref/JapanSummit100.csv", header = TRUE, fileEncoding="UTF-8")
lat <- as.numeric(as.character(x$緯度))
lon <- as.numeric(as.character(x$経度))
dt <- data.frame("Name"=x$山名, "lat"=lat, "lon"=lon, "elev"=x$標高)
dt %>% 
  leaflet %>% 
  addTiles() %>% 
  addCircleMarkers(lat=~lat, lng=~lon, radius = ~elev/1000, label = ~Name) 


```

Column {data-width=40%}
-----------------------------------------
### Table

```{r mountain_table}

dt %>% 
  datatable(
          rownames=FALSE, 
          filter='top', 
          options=list(
            autoWidth=TRUE,
            pageLength=16
          )
        )



```


## Japan 100 famous water(2021)
===============================================

Column {data-width=60%}
--------------------------------------

### Map

```{r water_map}}

x <- read.csv("http://www.dinov.tokyo/Data/JP_Pref/JapanWater100.csv", header = TRUE, fileEncoding="UTF-8")
lat <- as.numeric(as.character(x$北緯))
lon <- as.numeric(as.character(x$東経))
dt_w <- data.frame("Name"=x$名称, "lat"=lat, "lon"=lon)
dt_w %>% 
  leaflet %>% 
  addTiles() %>% 
  addCircleMarkers(lat=~lat, lng=~lon, radius = 1, label = ~Name) 


```

Column {data-width=40%}
-----------------------------------------
### Table

```{r water_table}

dt_w %>% 
  datatable(
          rownames=FALSE, 
          filter='top', 
          options=list(
            autoWidth=TRUE,
            pageLength=16
          )
        )



```

## 稲城　医療機関
==========================================

```{r inagi_hospital}

library(tidyverse)
library(leaflet)

dat <- read.csv("012.csv", fileEncoding = "UTF-8", header=TRUE) 

dat %>% 
  select(Name="名称", lat="緯度", lng="経度", tel="電話番号") %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat = ~lat, lng = ~lng, popup = ~ paste(Name, tel))


```